on: workflow_dispatch

jobs:
 build:
  runs-on: ubuntu-latest
  env:
    RUNNER_TOOL_CACHE: /toolcache
    
  steps:
    - name: git-checkout
      uses: actions/checkout@v4
    - name: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: setup-pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8.5.1
        run_install: false
        standalone: true
        dest: ~/setup-pnpm
    - name: build
      run: |
        pnpm i
        pnpm run build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: |
          dist
          !dist/**/*.md
    - name: Build release folder
      run: |
        mkdir -p release/TunnelDeck
        cp -r defaults release/TunnelDeck
        cp -r dist release/TunnelDeck
        cp  LICENSE release/TunnelDeck
        cp  README.md release/TunnelDeck
        cp  main.py release/TunnelDeck
        cp  package.json release/TunnelDeck
        cp  plugin.json release/TunnelDeck
    - name: Archive release as zip
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: |
          release
          
